### ISSUE TITLE
I can't read the readme.md

### ISSUE THREAD

**Issue by jonathandgough** [rkhullar/terraform-utils#5]
Hi, I am looking forward to using this package. i believe it will revolutionize my tera-form world. However, I am having trouble knowing how to use this utils package. Could you please provide a readme.md? 

Thanks, 

Really looking forward to this utility.

**Comment by Denisolt** [comment]
Experiencing a similar issue here as well. Any support @rkhullar ?

**Comment by msdocs** [comment]
It used to work a few months ago which version of python are you running @jonathandgough and @Denisolt

**Comment by jonathandgough** [comment]
@msdocs This is a python package? It is hard to tell without a readme. Waiting with anticipation.

**Comment by TaraLiang93** [comment]
It should still be working but it will be great if other people learn how to use it.

**Comment by msdocs** [comment]
@jonathandgough yes it is a python package and it's published on pypi. Honestly without a readme I don't see how anyone would know that

**Comment by msdocs** [comment]
> It should still be working but it will be great if other people learn how to use it.

Make a wiki pls @TaraLiang93

**Comment by msdocs** [comment]
@rkhullar is this compatible with terragrunt as well or just terraform

**Comment by jonathandgough** [comment]
Now that is a gorgeous README! @rkhullar !!!
